# Generated by Django 4.2.4 on 2023-10-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0009_rename_producct_wishlist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('product_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_offer_images', models.ImageField(null=True, upload_to='photos/offerimages')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('product_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_offer_images', models.ImageField(null=True, upload_to='photos/offerimages')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='myapp.category')),
            ],
        ),
    ]
