# Generated by Django 4.2.4 on 2023-10-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='product_offer_images',
            new_name='category_offer_image',
        ),
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='product_offer_slug',
            new_name='category_offer_slug',
        ),
    ]
