# Generated by Django 4.2.4 on 2023-10-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_categoryoffer_category_categoryoffer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='product_offer_images',
            new_name='product_offer_image',
        ),
    ]
