# Generated by Django 4.2.4 on 2023-10-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon_minimum_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
    ]
