# Generated by Django 4.2.4 on 2023-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_code_coupon_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
