# Generated by Django 4.2.4 on 2023-10-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_discount',
            field=models.IntegerField(null=True),
        ),
    ]
