# Generated by Django 4.2.4 on 2023-10-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='producct',
            new_name='product',
        ),
    ]
