# Generated by Django 4.2.4 on 2023-10-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_producct_wishlist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='bannertop')),
                ('deal', models.CharField(default='', max_length=50)),
                ('sale', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
