# Generated by Django 4.2.4 on 2023-10-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_banner_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_area',
            name='image',
            field=models.ImageField(upload_to='photos/bannertop'),
        ),
    ]
