# Generated by Django 4.2.4 on 2023-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_banner_area_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='sale',
        ),
        migrations.AddField(
            model_name='banner_area',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='banner_area',
            name='tag_line',
            field=models.CharField(default='', max_length=50),
        ),
    ]
