# Generated by Django 4.2.4 on 2023-10-20 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
