# Generated by Django 4.2.4 on 2023-11-02 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
